"""
Zip Handler
Assembles package components and creates downloadable zip file
"""

import io
import zipfile
from typing import Dict, Any
from pathlib import Path

class ZipHandler:
    """Creates zip packages for download"""

    def create_package(
        self,
        questionnaire_content: str,
        setup_instructions: str,
        file_structure: Dict[str, str],
        startup_hook: str
    ) -> bytes:
        """
        Create complete zip package

        Args:
            questionnaire_content: questionnaire.md content
            setup_instructions: setup-instructions.md content
            file_structure: Dict of file paths to contents
            startup_hook: startup-hook-example.sh content

        Returns:
            Zip file as bytes
        """
        # Create in-memory zip file
        zip_buffer = io.BytesIO()

        with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
            # Add questionnaire
            zip_file.writestr('questionnaire.md', questionnaire_content)

            # Add setup instructions
            zip_file.writestr('setup-instructions.md', setup_instructions)

            # Add file structure template
            for file_path, content in file_structure.items():
                zip_file.writestr(f'file-structure/{file_path}', content)

            # Add startup hook example
            zip_file.writestr('examples/startup-hook-example.sh', startup_hook)

            # Add README
            readme = self._create_readme()
            zip_file.writestr('README.md', readme)

        # Get bytes
        zip_buffer.seek(0)
        return zip_buffer.getvalue()

    def _create_readme(self) -> str:
        """Generate README.md for package"""
        return """# AI-Brain Integration Setup Package

Thank you for downloading your customized AI-brain integration package!

## What's Included

- `questionnaire.md` - Your personalized questionnaire
- `setup-instructions.md` - Step-by-step implementation guide
- `README.md` - Quick start guide
- `file-structure/` - Template folder structure
- `examples/` - Example configuration files

## Quick Start

1. Read `setup-instructions.md`
2. Answer questions in `questionnaire.md`
3. Create your `.memory/` folder
4. Set up Claude Code hooks
5. Start using your AI memory system!

## Need Help?

Refer to `setup-instructions.md` for detailed guidance.

---

**Generated by AI-Brain Setup Application**
"""
